export const currencies = [
    { value: 'USD', label: 'USD - United States Dollar', symbol: '$' },
    { value: 'EUR', label: 'EUR - Euro', symbol: '€' },
    { value: 'GBP', label: 'GBP - British Pound', symbol: '£' },
    { value: 'JPY', label: 'JPY - Japanese Yen', symbol: '¥' },
    { value: 'AUD', label: 'AUD - Australian Dollar', symbol: '$' },
    { value: 'CAD', label: 'CAD - Canadian Dollar', symbol: '$' },
    { value: 'CHF', label: 'CHF - Swiss Franc', symbol: 'CHF' },
    { value: 'CNY', label: 'CNY - Chinese Yuan', symbol: '¥' },
    { value: 'SEK', label: 'SEK - Swedish Krona', symbol: 'kr' },
    { value: 'NZD', label: 'NZD - New Zealand Dollar', symbol: '$' },
    { value: 'MXN', label: 'MXN - Mexican Peso', symbol: '$' },
    { value: 'SGD', label: 'SGD - Singapore Dollar', symbol: '$' },
    { value: 'HKD', label: 'HKD - Hong Kong Dollar', symbol: '$' },
    { value: 'NOK', label: 'NOK - Norwegian Krone', symbol: 'kr' },
    { value: 'KRW', label: 'KRW - South Korean Won', symbol: '₩' },
    { value: 'TRY', label: 'TRY - Turkish Lira', symbol: '₺' },
    { value: 'RUB', label: 'RUB - Russian Ruble', symbol: '₽' },
    { value: 'INR', label: 'INR - Indian Rupee', symbol: '₹' },
    { value: 'BRL', label: 'BRL - Brazilian Real', symbol: 'R$' },
    { value: 'ZAR', label: 'ZAR - South African Rand', symbol: 'R' },
    { value: 'PHP', label: 'PHP - Philippine Peso', symbol: '₱' },
    { value: 'IDR', label: 'IDR - Indonesian Rupiah', symbol: 'Rp' },
    { value: 'MYR', label: 'MYR - Malaysian Ringgit', symbol: 'RM' },
    { value: 'THB', label: 'THB - Thai Baht', symbol: '฿' },
    { value: 'VND', label: 'VND - Vietnamese Dong', symbol: '₫' },
    { value: 'PLN', label: 'PLN - Polish Zloty', symbol: 'zł' },
];
